# Generated by Django 5.0 on 2024-01-06 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('alias', models.CharField(blank=True, max_length=30, verbose_name='Alias')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='Mobile')),
                ('npi_number', models.CharField(blank=True, max_length=20, verbose_name='NPI Number')),
                ('dea_number', models.CharField(blank=True, max_length=20, verbose_name='DEA Number')),
                ('nadean_number', models.CharField(blank=True, max_length=20, verbose_name='NADEAN Number')),
                ('state_license', models.CharField(blank=True, choices=[("'AL'", " 'Alabama'"), ("'AK'", " 'Alaska'"), ("'AZ'", " 'Arizona'"), ("'AR'", " 'Arkansas'"), ("'CA'", " 'California'"), ("'CO'", " 'Colorado'"), ("'CT'", " 'Connecticut'"), ("'DE'", " 'Delaware'"), ("'FL'", " 'Florida'"), ("'GA'", " 'Georgia'"), ("'HI'", " 'Hawaii'"), ("'ID'", " 'Idaho'"), ("'IL'", " 'Illinois'"), ("'IN'", " 'Indiana'"), ("'IA'", " 'Iowa'"), ("'KS'", " 'Kansas'"), ("'KY'", " 'Kentucky'"), ("'LA'", " 'Louisiana'"), ("'ME'", " 'Maine'"), ("'MD'", " 'Maryland'"), ("'MA'", " 'Massachusetts'"), ("'MI'", " 'Michigan'"), ("'MN'", " 'Minnesota'"), ("'MS'", " 'Mississippi'"), ("'MO'", " 'Missouri'"), ("'MT'", " 'Montana'"), ("'NE'", " 'Nebraska'"), ("'NV'", " 'Nevada'"), ("'NH'", " 'New Hampshire'"), ("'NJ'", " 'New Jersey'"), ("'NM'", " 'New Mexico'"), ("'NY'", " 'New York'"), ("'NC'", " 'North Carolina'"), ("'ND'", " 'North Dakota'"), ("'OH'", " 'Ohio'"), ("'OK'", " 'Oklahoma'"), ("'OR'", " 'Oregon'"), ("'PA'", " 'Pennsylvania'"), ("'RI'", " 'Rhode Island'"), ("'SC'", " 'South Carolina'"), ("'SD'", " 'South Dakota'"), ("'TN'", " 'Tennessee'"), ("'TX'", " 'Texas'"), ("'UT'", " 'Utah'"), ("'VT'", " 'Vermont'"), ("'VA'", " 'Virginia'"), ("'WA'", " 'Washington'"), ("'WV'", " 'West Virginia'"), ("'WI'", " 'Wisconsin'"), ("'WY'", " 'Wyoming'")], max_length=20, verbose_name='State License')),
                ('primary_license_number', models.CharField(blank=True, max_length=30, verbose_name='Primary License Number')),
                ('secondary_license_number', models.CharField(blank=True, max_length=30, verbose_name='Secondary License Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('receive_text_notifications', models.BooleanField(default=False, verbose_name='Receive Text Notifications')),
                ('receive_call_notifications', models.BooleanField(default=False, verbose_name='Receive Call Notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
